In [ ]:

### ! WARNING, NO CONDA ON DELTAGER COMPUTERE ! ### 
%conda install python-graphviz

## Imports

I behøver som sådan ikke vide det, men følgende pakker er til følgende ting

- Numpy: Bare smart at have til matricer og saadan
- Sklearn: Har premade funktioner til at lave og traene decision trees, blandt andet
- os er en af python's indbyggede pakker til meget homekeeping ting og den slags
- matplolib er til plotting
- graphviz er udelukkende for at plotte decision trees paa en smart maade

In [ ]:
import numpy as np
from sklearn import tree
from os import getcwd
import matplotlib.pyplot as plt
from matplotlib.image import imread
import graphviz

In [13]:

# Names of data objects
dataobjectNames = [
    'Human',
    'Python',
    'Salmon',
    'Whale',
    'Frog',
    'Komodo dragon',
    'Bat',
    'Pigeon',
    'Cat',
    'Leopard shark',
    'Turtle',
    'Penguin',
    'Porcupine',
    'Eel',
    'Salamander',
    ]

# Attribute names
attributeNames = [
    'Body temperature',
    'Skin cover',
    'Gives birth',
    'Aquatic creature',
    'Aerial creature',
    'Has legs',
    'Hibernates'
    ]

# Attribute values
data_points = np.asarray(np.mat('''
    1 1 1 0 0 1 0;
    0 2 0 0 0 0 1;
    0 2 0 1 0 0 0;
    1 1 1 1 0 0 0;
    0 0 0 2 0 1 1;
    0 2 0 0 0 1 0;
    1 1 1 0 1 1 1;
    1 3 0 0 1 1 0;
    1 4 1 0 0 1 0;
    0 2 1 1 0 0 0;
    0 2 0 2 0 1 0;
    1 3 0 2 0 1 0;
    1 5 1 0 0 1 1;
    0 2 0 1 0 0 0;
    0 0 0 2 0 1 1 '''))

# Class indices
targets = np.asarray(np.mat('3 4 2 3 0 4 3 1 3 2 4 1 3 2 0').T).squeeze()

# Class names
classNames = ['Amphibian', 'Bird', 'Fish', 'Mammal', 'Reptile']
    
# Number data objects, attributes, and classes
N, M = X.shape

print(f"Der er {len(classNames)} forskellige klasser")
print(f"Der er {X.shape[0]} forskellige datapunkter, hver med {X.shape[1]} features")

Der er 5 forskellige klasser
Der er 15 forskellige datapunkter, hver med 7 features


In [36]:
# Fit Decision tree classifier, Gini split criterion, no pruning
criterion = 'gini' # {“gini”, “entropy”, “log_loss”},
dtc = tree.DecisionTreeClassifier(criterion=criterion, min_samples_split=2)
dtc = dtc.fit(data_points=X, targets=y)

In [17]:
# Plot træet (behøver ikke forstå denne kode)
fname = 'tree_' + criterion
proportion = False
out = tree.export_graphviz(dtc, out_file=fname + '.gvz', feature_names=attributeNames, rounded=True, proportion=proportion)
src = graphviz.Source.from_file(fname + '.gvz')
src.view()

'tree_gini.gvz.pdf'

# Decision Trees med Iris datasættet

"Hvilken en af 3 forskellige arter er en blomst, hvis vi kigger på længden og bredden af dens to forskellige slags blade"

![](iris.png)

Dette er spørgsmålet der stilles i nok det andet mest velkendte datasæt inden for machine learning. Som så ofte er tilfædet i machine learning, er det velkendt netop fordi det er hylende morsomt nemt at løse spørgsmålet det stiller.

I decision trees er det specielt spændende at kigge på, fordi vores features lige pludselig er udelukkende kontinuerte; vi spørger altså ikke hvorvidt blomsterne har én ud af en endelig mængde forskellige værdier, eller om de opfylder én ud af en række af krav. Vi spørger blot hvor lange og hvor brede deres 2 slags blade er (petals og sepals). Dette giver os 4 features til at bestemme 3 klasser, altså om en given blomst er enten:

- Iris Versicolor
- Iris Setosa
- Iris Virginica

I denne øvelse vil vi gøre følgende ting:


## 1. Load Iris datasættet

Iris er så velkendt (og fylder så lidt), at man bare kan hente datasættet med indbyggede funktioner i mange Python pakker. Vi bruger Sklearn.

(Bemærk (som så meget i machine learning))


## 2. Fitter et decision tree til datasættet

Ligesom før med eksemeplet i dyreriget, fitter vi et decision tree og undersøger hvad dette gør.


## 3. Undersøger opførslen når vi manipulerer datasættet

Decision trees, ligesom så meget andet machine learning, har en slags implicit intelligens. Hvis vi gør sådan at en klasse er overreræsenteret, burde vores decision tree udvikle sig lignende for hurtigere at kunne bestemme den rigtige klasse.

## 1. Load Iris datasættet

In [33]:
# Load iris datasættet
import sklearn.datasets

iris = sklearn.datasets.load_iris()


# Iris datasættet er som sagt ikke bare et numpy array :(((, så for at tilgå dataen skal vi bruge nogle af datasættets egenskaber (properties i Python) således:

print(f"Der er {iris.data.shape[0]} datapunkter, hver med {iris.data.shape[1]} features \n")

print(f"Datasaettets features hedder {iris.feature_names} \n")

print(f"Et udsnit af de foerste 10 punkter er: \n {iris.data[:10]} \n")

print(f"Disse 10 foerste punkters targets (deres y-vaerdier er): \n {iris.target[:10]} \n")

Der er 150 datapunkter, hver med 4 features 

Datasaettets features hedder ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] 

Et udsnit af de foerste 10 punkter er: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]] 

Disse 10 foerste punkters targets (deres y-vaerdier er): 
 [0 0 0 0 0 0 0 0 0 0] 



### 1.1 Forståelse for dataen

**Det der adskiller ML ingeniører fra resten af pøblen er en basal viden for hvad de arbejder med, heriblandt dataen.
**

*Ser du nogle som helst problemer med denne data, enten dens x- eller y-værdier? *

In [34]:
# Randomly permute dataen (uden at scramble hvilke x værdier der hører til hvilke y værdier)

new_ordering = np.random.permutation(len(iris.data))

iris.data = iris.data[new_ordering]
iris.target = iris.target[new_ordering]

print(f"De 10 nye første værdier er nu \n {iris.data[:10]} \n")

print(f"Med tilhørende nye værdier: \n {iris.target[:10]} \n")



Et udsnit af de foerste 10 punkter er: 
 [[4.8 3.  1.4 0.1]
 [6.3 2.9 5.6 1.8]
 [7.2 3.6 6.1 2.5]
 [7.4 2.8 6.1 1.9]
 [5.7 2.9 4.2 1.3]
 [5.  3.3 1.4 0.2]
 [5.1 3.3 1.7 0.5]
 [6.4 2.8 5.6 2.1]
 [6.3 3.3 4.7 1.6]
 [5.4 3.9 1.3 0.4]] 

Disse 10 foerste punkters targets (deres y-vaerdier er): 
 [0 2 2 2 1 0 0 2 1 0] 



## 2. Fit dit decision tree



### 1.2 Lav dit decision tree

**Her skal du forstå dig for den mest ædle af egenskaber i ML udviklerens værktøjskasse: Plagiat**

*Brug koden fra dyre eksemplet fra før til at fitte et decision tree til iris datasættet*

In [29]:
type(iris.data)

iris.data.shape

iris.feature_names

iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3