# 1: NumPy

Når man er blevet mere vant til nogle af de muligheder Python i sig selv til-
byder, så er det meget almindeligt at udvide Pythons repertoire ved at gøre
det man kalder "at importere pakker". Pakker er udvidelser til standard
Python som basalt set kommer med en række foruddefinerede funktioner til
en lang række ting. Hvis man gerne vil arbejde med matematik, så er en af
de mest brugte pakker numpy.

For at få hentet alle de funktioner numpy kommer med, skal man først
importere pakken, hvilken man oftest vil gøre helt i starten af sit script.
Man kan importere pakken på en række måder, men en almindelig måde at
gøre det på er følgende

In [1]:
import numpy as np

På denne måde giver vi numpy pakken et navn i vores kode, i dette tilfælde
"np". Navnet vi har givet pakken skal bruges, når vi skal kalde funktioner
fra pakken. En af de vigtigste funktioner fra numpy er det man kalder et
numpy array.

For selv at lave en numpy array kan man skrive følgende:

In [5]:
mit_numpy_array = np.array([1, 2, 3])

print(mit_numpy_array)

[1 2 3]


Her kalder man en funktion fra numpy ved at skrive "np", og vi fortæller
Python at det er "array" funktionen vi kalder ved at skrive ".array" efter
"np". Det input vi giver til denne funktion er en liste med tallene 1, 2 og 3.

Man kan betragte enkelte tal i et array ved brug af [] paranteser til indeksering

In [27]:
mit_numpy_array = np.array([1, 2, 3])

første_element = mit_numpy_array[0]
andet_element = mit_numpy_array[1]
tredje_element = mit_numpy_array[2]

print("første_element:", første_element,
     "\n andet_element:", andet_element,
     "\n tredje_element:", tredje_element)

første_element: 1 
 andet_element: 2 
 tredje_element: 3


Her skal man være opmærksom på, at Python nul-indekserer. Det betyder bare, at man starter fra nul, når man tæller.

Arrays undersøtter aritmetiske operationer.

In [2]:
# Her lægger vi to numpy arrays sammen
numpy_array_1 = np.array([1, 2, 3])
numpy_array_2 = np.array([0, 0, 1])

numpy_array_sum = numpy_array_1 + numpy_array_2

print(numpy_array_sum)

[1 2 4]


Numpy arrays minder lidt om vektorer fra matematik og er dermed
enormt brugbare til at regne på netop vektorer i Python. Man kan også lægge to arrays i forlængelse af hinanden ved brug af concatenate funktionen, også fra numpy.

In [3]:
# Her lægger vi to numpy arrays i forlængelse af hinanden
numpy_array_1 = np.array([1, 2, 3])
numpy_array_2 = np.array([0, 0, 1])

numpy_array_total = np.concatenate([numpy_array_1, numpy_array_2])

print(numpy_array_total)

[1 2 3 0 0 1]


numpy kan også bruges til, at regne med matricer.

In [12]:
min_matrix = np.array([[1, 2], [3, 4]])

print(min_matrix)

[[1 2]
 [3 4]]


Her er indeksering lidt spøjst, da en matrix er et array, som består af arrays.

In [28]:
min_matrix = np.array([[1, 2], [3, 4]])

første_række = min_matrix[0]
første_tal = min_matrix[0][0]

print("Første element i matrix (første række):", første_række,
     "\n Første element i første element i matrix (første tal i første række):", første_tal)

Første element i matrix (første række): [1 2] 
 Første element i første element i matrix (første tal i første række): 1


Vil man gerne lave operationer på kolonner i stedet for rækker, får man brug for : til at "slice" matricer XXX

In [34]:
min_matrix = np.array([[1, 2], [3, 4]])

print(min_matrix[:,0])

[1 3]


Hvis man gerne vil lave operationer med matricer, såsom at lægge to sam-
men eller trække en fra en anden, så bruger man bare de almindelige operationer
"+" og "-". Matrixmultiplikation med arrays bruger dog @ i stedet for *.

In [16]:
matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[2, 2], [2, 2]])

matrix_sum = matrix_1 + matrix_2
matrix_differens = matrix_1 - matrix_2
matrix_produkt = matrix_1 @ matrix_2

print("matrix_sum:\n", matrix_sum,
      "\n matrix_differens:\n", matrix_differens,
      "\n matrix_produkt:\n", matrix_produkt)

matrix_sum:
 [[3 4]
 [5 6]] 
 matrix_differens:
 [[-1  0]
 [ 1  2]] 
 matrix_produkt:
 [[ 6  6]
 [14 14]]


Hvis man vil have prikproduktet af to arrays kan man bruge np.dot

In [17]:
numpy_array_1 = np.array([1, 2, 3])
numpy_array_2 = np.array([0, 0, 1])

prikprodukt = np.dot(numpy_array_1, numpy_array_2)

print(prikprodukt)

3


Man kan også transponere og invertere matricer.

In [23]:
min_matrix = np.array([[1, 2], [3, 4]])

min_transponerede_matrix = min_matrix.T    # Man kan også bruge np.transpose() i stedet for .T
min_inverterede_matrix = np.linalg.inv(min_matrix)

print("min_matrix:\n", min_matrix,
      "\n min_transponerede_matrix:\n", min_transponerede_matrix,
      "\n min_inverterede_matrix:\n", min_inverterede_matrix)

min_matrix:
 [[1 2]
 [3 4]] 
 min_transponerede_matrix:
 [[1 3]
 [2 4]] 
 min_inverterede_matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


En anden numpy funktion, som kan være relevant når man arbejder med
lineær algebra, er np.shape(). Dette er en funktion, der tager et array som
input og giver et output, der tilsvarer dimensionen af det input man har
givet funktionen. Dette kan være ret praktisk når man gerne vil undersøge
om de matricer og vektorer man arbejder med faktisk har de dimensioner,
som man forventer at de har.

In [24]:
min_matrix = np.array([[1, 2], [3, 4]])

min_matrix_dimension = np.shape(min_matrix)

print(min_matrix_dimension)

(2, 2)


Nu er det selvfølgelig rimeligt nemt at se, at vores matrix er en 2×2 matrix,
men hvis man arbejder med meget større datasæt og matricer, så er det
pludseligt ikke så nemt at se at ens matrix er 1572 × 489 eller hvad den nu
måtte være. Der er np.shape() meget brugbar

Der findes selvfølgelig et hav af andre ting som numpy er i stand til at gøre,
og her er Google virkelig jeres bedste ven. Herunder er der lavet en tabel
med nogle af de mere gængse funktioner i numpy, især relateret til
matematik og statistik, men hvis man skal ud i noget mere specifikt så er
en hurtig Google søgning ofte meget hjælpsom.

| Numpy Funktion   | Beskrivelse |
|------------------|-------------|
| np.sin()         | Dette giver dig sinus til hvad end input du giver funktionen. |
| np.cos()         | Dette giver dig cosinus til hvad end input du giver funktionen. |
| np.tan()         | Dette giver dig tangens til hvad end input du giver funktionen. |
| np.exp()         | Dette tager e^x af hvad end input du giver funktionen. |
| np.pi            | Dette giver dig værdien af pi. |
| np.mean()        | Dette giver gennemsnittet af det input du giver. |
| np.var()         | Dette giver variansen af det input du giver. |
| np.std()         | Dette giver standardafvigelsen af det input du giver. |
| np.zeros()       | Dette giver dig en numpy array fyldt med nuller som har en længde tilsvarende den værdi du giver som input. |
| np.array()       | Dette opretter en numpy array baseret på en liste eller en anden sekvens af data. |
| np.concatenate() | Dette sammensætter arrays. |
| np.dot()         | Dette udfører matrix-vektor eller matrix-matrix multiplikation. |
| np.linalg.inv()  | Dette giver den inverse af en matrix. |
| np.shape         | Dette giver formen (dimensionerne) af en numpy array. |
| .T               | Dette transponerer et array. |
| @                | Dette bruges til matrixmultiplikation. |

### Opgaver

##### Opgave 1.1
Definder følgende to matricer ved brug af numpy

$$
A =
\begin{bmatrix}
8 & 32 \\
9 & 1
\end{bmatrix}
$$

$$
B =
\begin{bmatrix}
5 & 4 \\
2 & 6
\end{bmatrix}
$$

Beregn følgende:

- $A + B$
- $A - B$
- $AB$
- $A^TB$
- $A^{-1}B$
- $A^{-1}A$

In [ ]:
# Din kode her

##### Opgave 1.2
Tag udganspunkt i matricerne A og B fra før. Beregn følgende:
- Summen af første række i A og anden række i B
- Differensen mellem første kolonne i A og anden kolonne i B
- Produktet af første tal i første række i A og andet tal af anden række i B

In [ ]:
XXX få tilrettet/færdigjort eksempler og tekst med indeksering hvor der bliver referert til elementer i arrays. Der mangler noget om slicing XXX Husk også at -1 refererer til sidste element. Tilføj også vstack og hstack til tabel XXX

# 2: Løkker

# 3: Funktioner

### Opgaver


##### Opgave 3.X
Skriv et program som afgører, hvorvidt en matrix er symmetrisk eller ej. Her menes der
med symmetrisk at matricen opfylder $A^T = A$

##### Opgave 3.X
Skriv et program som finder middelværdien af hver række i en vilkårlig matrix.

# 4: Matplotlib